export const DRIVER_COLORS = ['#3b82f6', '#22c55e', '#f59e0b', '#8b5cf6', '#06b6d4', '#f97316'];

export const TRACKS = [
  'Algarve International Circuit (Portimão)',
  'Autodromo Internazionale Enzo e Dino Ferrari (Imola)',
  'Autódromo José Carlos Pace (Interlagos)',
  'Bahrain International Circuit',
  'Circuit of the Americas',
  'Circuit de la Sarthe',
  'Fuji International Speedway',
  'Lusail International Circuit',
  'Monza',
  'Sebring',
  'Spa-Francorchamps',
  'Circuit de Barcelona-Catalunya',
  'Circuit Paul Ricard',
  'Silverstone',
  'COTA National',
  'Bahrain International Endurance Circuit',
  'Bahrain International Outer Circuit',
  'Bahrain International Paddock Circuit',
  'Fuji Classic Layout (No Chicane)',
  'Circuit de la Sarthe Mulsanne No Chicanes',
  'Lusail International Circuit Short',
  'Monza Curva Grande Layout',
  'Sebring School Circuit',
  'Spa Endurance Layout',
];
