export const TRACKS = [
  'Bahrain International Endurance Circuit',
  'Bahrain International Outer Circuit',
  'Bahrain International Paddock Circuit',
  'Circuit de Barcelona-Catalunya',
  'Circuit de la Sarthe',
  'Circuit de la Sarthe Mulsanne No Chicanes',
  'Circuit Paul Ricard',
  'COTA National',
  'Fuji Classic Layout (No Chicane)',
  'Le Mans',
  'Lusail International Circuit Short',
  'Monza',
  'Monza Curva Grande Layout',
  'Nürburgring',
  'Road Atlanta',
  'Sebring',
  'Sebring School Circuit',
  'Silverstone',
  'Spa Endurance Layout',
  'Spa-Francorchamps',
  'Suzuka',
];
